// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_channel.sql

package repository

import (
	"context"
)

const createPaymentChannel = `-- name: CreatePaymentChannel :one
INSERT INTO payment_channels (
  code,
  name,
  gateway_fee_fixed,
  gateway_fee_percentage,
  platform_fee_fixed,
  platform_fee_percentage
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, code, name, gateway_fee_fixed, gateway_fee_percentage, platform_fee_fixed, platform_fee_percentage, is_active, created_at
`

type CreatePaymentChannelParams struct {
	Code                  string
	Name                  string
	GatewayFeeFixed       int64
	GatewayFeePercentage  int64
	PlatformFeeFixed      int64
	PlatformFeePercentage int64
}

func (q *Queries) CreatePaymentChannel(ctx context.Context, arg CreatePaymentChannelParams) (PaymentChannel, error) {
	row := q.db.QueryRow(ctx, createPaymentChannel,
		arg.Code,
		arg.Name,
		arg.GatewayFeeFixed,
		arg.GatewayFeePercentage,
		arg.PlatformFeeFixed,
		arg.PlatformFeePercentage,
	)
	var i PaymentChannel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.GatewayFeeFixed,
		&i.GatewayFeePercentage,
		&i.PlatformFeeFixed,
		&i.PlatformFeePercentage,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentChannelByCode = `-- name: GetPaymentChannelByCode :one
SELECT id, code, name, gateway_fee_fixed, gateway_fee_percentage, platform_fee_fixed, platform_fee_percentage, is_active, created_at FROM payment_channels WHERE code = $1
`

func (q *Queries) GetPaymentChannelByCode(ctx context.Context, code string) (PaymentChannel, error) {
	row := q.db.QueryRow(ctx, getPaymentChannelByCode, code)
	var i PaymentChannel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.GatewayFeeFixed,
		&i.GatewayFeePercentage,
		&i.PlatformFeeFixed,
		&i.PlatformFeePercentage,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentChannelByID = `-- name: GetPaymentChannelByID :one
SELECT id, code, name, gateway_fee_fixed, gateway_fee_percentage, platform_fee_fixed, platform_fee_percentage, is_active, created_at FROM payment_channels WHERE id = $1
`

func (q *Queries) GetPaymentChannelByID(ctx context.Context, id int32) (PaymentChannel, error) {
	row := q.db.QueryRow(ctx, getPaymentChannelByID, id)
	var i PaymentChannel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.GatewayFeeFixed,
		&i.GatewayFeePercentage,
		&i.PlatformFeeFixed,
		&i.PlatformFeePercentage,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentChannels = `-- name: GetPaymentChannels :many
SELECT id, code, name, gateway_fee_fixed, gateway_fee_percentage, platform_fee_fixed, platform_fee_percentage, is_active, created_at FROM payment_channels
`

func (q *Queries) GetPaymentChannels(ctx context.Context) ([]PaymentChannel, error) {
	rows, err := q.db.Query(ctx, getPaymentChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentChannel
	for rows.Next() {
		var i PaymentChannel
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.GatewayFeeFixed,
			&i.GatewayFeePercentage,
			&i.PlatformFeeFixed,
			&i.PlatformFeePercentage,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
