// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_identities.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthIdentityLocal = `-- name: CreateAuthIdentityLocal :exec
INSERT INTO auth_identities (
  user_id,
  provider,
  provider_id,
  password_hash
) VALUES (
  $1, $2, $3, $4
)
`

type CreateAuthIdentityLocalParams struct {
	UserID       uuid.UUID
	Provider     string
	ProviderID   string
	PasswordHash pgtype.Text
}

func (q *Queries) CreateAuthIdentityLocal(ctx context.Context, arg CreateAuthIdentityLocalParams) error {
	_, err := q.db.Exec(ctx, createAuthIdentityLocal,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.PasswordHash,
	)
	return err
}

const getAuthIdentityByEmail = `-- name: GetAuthIdentityByEmail :one
SELECT id, user_id, provider, provider_id, password_hash, totp_secret, totp_enabled, meta, last_login_at, created_at, updated_at, deleted_at FROM auth_identities WHERE provider = 'local' AND provider_id = $1
`

func (q *Queries) GetAuthIdentityByEmail(ctx context.Context, providerID string) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByEmail, providerID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.Meta,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
