// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"sakucita/internal/domain"
)

type AuthIdentity struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Provider     string
	ProviderID   string
	PasswordHash pgtype.Text
	TotpSecret   pgtype.Text
	TotpEnabled  bool
	Meta         domain.JSONB
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type Role struct {
	ID   int32
	Name string
}

type Session struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	DeviceID       string
	RefreshTokenID pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
	Revoked        bool
	Meta           domain.JSONB
	CreatedAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
}

type User struct {
	ID            uuid.UUID
	Email         string
	EmailVerified bool
	Phone         pgtype.Text
	Name          string
	Nickname      string
	ImageUrl      pgtype.Text
	SingleSession bool
	Meta          domain.JSONB
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type UserRole struct {
	UserID uuid.UUID
	RoleID int32
}
