// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"sakucita/internal/domain"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  user_id,
  device_id,
  refresh_token_id,
  expires_at,
  meta
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, user_id, device_id, refresh_token_id, expires_at, revoked, meta, created_at, last_used_at
`

type CreateSessionParams struct {
	UserID         uuid.UUID
	DeviceID       string
	RefreshTokenID pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
	Meta           domain.JSONB
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.DeviceID,
		arg.RefreshTokenID,
		arg.ExpiresAt,
		arg.Meta,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenID,
		&i.ExpiresAt,
		&i.Revoked,
		&i.Meta,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeAllSessionsByUserID = `-- name: RevokeAllSessionsByUserID :exec
UPDATE sessions SET revoked = TRUE WHERE user_id = $1
`

func (q *Queries) RevokeAllSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsByUserID, userID)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions SET revoked = TRUE WHERE id = $1 AND user_id = $2
`

type RevokeSessionByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, arg.ID, arg.UserID)
	return err
}
