// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"sakucita/internal/domain"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  phone,
  name,
  nickname
) VALUES (
  $1, $2, $3, $4
) RETURNING id, email, email_verified, phone, name, nickname, image_url, single_session, meta, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email    string
	Phone    pgtype.Text
	Name     string
	Nickname string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Phone,
		arg.Name,
		arg.Nickname,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Name,
		&i.Nickname,
		&i.ImageUrl,
		&i.SingleSession,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified, phone, name, nickname, image_url, single_session, meta, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Name,
		&i.Nickname,
		&i.ImageUrl,
		&i.SingleSession,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified, phone, name, nickname, image_url, single_session, meta, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Name,
		&i.Nickname,
		&i.ImageUrl,
		&i.SingleSession,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIDWithRoles = `-- name: GetUserByIDWithRoles :one
SELECT 
    u.id, u.email, u.email_verified, u.phone, u.name, u.nickname, u.image_url, u.single_session, u.meta, u.created_at, u.updated_at, u.deleted_at,
    COALESCE(
      json_agg(
        json_build_object(
          'id', r.id,
          'name', r.name
        )
      ) FILTER (WHERE r.id IS NOT NULL),'[]'
    )::JSONB AS roles
FROM users u
LEFT JOIN user_roles ur ON u.id = ur.user_id
LEFT JOIN roles r ON ur.role_id = r.id
WHERE u.id = $1 AND u.deleted_at IS NULL
GROUP BY u.id
`

type GetUserByIDWithRolesRow struct {
	ID            uuid.UUID
	Email         string
	EmailVerified bool
	Phone         pgtype.Text
	Name          string
	Nickname      string
	ImageUrl      pgtype.Text
	SingleSession bool
	Meta          domain.JSONB
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	Roles         []byte
}

func (q *Queries) GetUserByIDWithRoles(ctx context.Context, id uuid.UUID) (GetUserByIDWithRolesRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDWithRoles, id)
	var i GetUserByIDWithRolesRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Name,
		&i.Nickname,
		&i.ImageUrl,
		&i.SingleSession,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Roles,
	)
	return i, err
}
