// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createUserRole = `-- name: CreateUserRole :exec
INSERT INTO user_roles (
  user_id,
  role_id
) VALUES(
  $1,$2
)
`

type CreateUserRoleParams struct {
	UserID uuid.UUID
	RoleID int32
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error {
	_, err := q.db.Exec(ctx, createUserRole, arg.UserID, arg.RoleID)
	return err
}
